apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-cluster-role
rules:
  - apiGroups:
      - "onecx.github.io"
    resources:
      - "microfrontends"
      - "microfrontends/status"
      - "microfrontends/finalizers"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "patch"
      - "update"
      - "create"
      - "delete"
